services:
  mysql:
    image: mysql:8.0.33
    ports:
      - 13306:3306 # host:container port
    volumes:
      - /Users/ahnkwanghyun/Documents/dev/faddy-payments-app/src/main/resources/initdb:/docker-entrypoint-initdb.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--lower_case_table_names=1'
    environment:
      MYSQL_ROOT_PASSWORD: testbed
      MYSQL_DATABASE: faddy_labs  # service-labs 대신 faddy_labs로 변경
      MYSQL_PASSWORD: testlabs
    networks:
      default_bridge:
        ipv4_address: 172.26.0.14

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      default_bridge:
        ipv4_address: 172.26.0.11

  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "19092:19092"
      - "19094:19094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://localhost:19094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT # 내 외부 보안 설정 추가
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://kafka-1:19094
      KAFKA_AUTO_CREATE_TOPIC_ENABLE: false
    networks:
      default_bridge:
        ipv4_address: 172.26.0.12

networks:
  default_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16