services:
  mysql:
    image: mysql:8.0.33
    ports:
      - 13306:3306 # host:container port
    volumes:
      - /Users/ahnkwanghyun/Documents/dev/faddy-payments-app/src/main/resources/initdb:/docker-entrypoint-initdb.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--lower_case_table_names=1'
    environment:
      MYSQL_ROOT_PASSWORD: testbed
      MYSQL_DATABASE: faddy_labs
      MYSQL_PASSWORD: testlabs
    networks:
      default_bridge:
        ipv4_address: 172.26.0.14

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      default_bridge:
        ipv4_address: 172.26.0.11

  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
    ports:
      - "19092:19092"
      - "19094:19094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://kafka-1:19094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://localhost:19094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPIC_ENABLE: false
    networks:
      default_bridge:
        ipv4_address: 172.26.0.12

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://172.26.0.12:19092'
      SCHEMA_REGISTRY_HOST_NAME: 'schema-registry'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8085'
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: 'INFO'
    ports:
      - 8085:8085
    depends_on:
      - kafka-1
    networks:
      default_bridge:
        ipv4_address: 172.26.0.13

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka-1
      - schema-registry
    ports:
      - 8081:8080
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=Fast-Ecommerce-Kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=172.26.0.12:19092
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://schema-registry:8085
    networks:
      default_bridge:
        ipv4_address: 172.26.0.17

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true
    networks:
      default_bridge:
        ipv4_address: 172.26.0.15
    depends_on:
      - app

  app:
    image: fastcamp/fast-ecommerce:latest
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev-docker
    depends_on:
      - mysql
    networks:
      default_bridge:
        ipv4_address: 172.26.0.16

networks:
  default_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16